name: check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: moonbit-community/setup-moonbit

      - name: Install dependencies
        run: |
          moon update
          moon check

      - name: Check code (deny warnings)
        run: moon check --deny-warn

      - name: Run tests
        run: moon test --target native
